### ISSUE TITLE
Join forces

### ISSUE THREAD

**Issue by michalfita** [sapir/gcc-rust#3]
Please join forces with https://github.com/redbrain/gccrs and don't try to do that by yourself. We need one good Rust frontend for GCC not multiple projects that both fail.

Thank you.

**Comment by Serentty** [comment]
The author of that other project seems keen on the idea of writing an entire frontend instead of just hijacking MIR. His idea is a lot more ambitious, but he has also been a lot less active. While I would be ecstatic to see his project succeed and for there to be multiple full compiler implementations, I expect to see this project get results a lot more quickly.

**Comment by sapir** [comment]
I agree with much of the discussion. Also:
1. I prefer Rust to C++, and know Rust better than I know C++, so I would have less to contribute to the other project, which is done in C++.
2. I think both projects may be useful for different reasons or in different cases. I would like the regular rust compiler to support all of gcc's backends, and I would also like an independent implementation like @redbrain is doing.
